name: "CI"

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      - name: Run tests
        run: make test